/**
 * Enterprise Auto Task Engine & Task State Manager
 * Handles automatic task creation, 13-step workflow state transitions, SLA tracking, and Audit Trail.
 */

import { EnterpriseTask, TaskStatus, TaskPriority, AutoTaskTriggerEvent, HospitalDepartmentId, TaskCategory } from "../types/enterpriseTask";

// Mock store initialized with realistic HIS enterprise tasks across departments
let mockEnterpriseTasks: EnterpriseTask[] = [
  {
    id: "task-001",
    taskNumber: "TSK-2026-001",
    titleAr: "إشعار نتيجة حرجة - فحص البوتاسيوم",
    titleEn: "Critical Result Notification - Serum Potassium (6.8 mmol/L)",
    descriptionAr: "نتيجة حرجة مرتفعة للبوتاسيوم للمريض يوسف أحمد في العناية المركزة. تتطلب تدخل فوري.",
    descriptionEn: "High critical potassium result for patient Youssef Ahmed in ICU. Requires immediate physician verification.",
    category: "laboratory",
    subtype: "critical_result_notification",
    priority: "critical",
    status: "escalated",
    originDepartment: "lis",
    targetDepartment: "icu",
    assignedToUserId: "usr-doc-01",
    assignedToUserName: "د. خالد العتيبي",
    assignedToRole: "Physician",
    createdById: "usr-lab-01",
    createdByName: "فني المختبر - أمل الشمري",
    patientId: "p1",
    patientMRN: "MRN-100234",
    patientNameAr: "يوسف أحمد الخالدي",
    patientNameEn: "Youssef Ahmed Al-Khaldi",
    visitId: "vst-001",
    orderId: "ord-lab-889",
    bedId: "bed-icu-04",
    roomId: "401-A",
    progressPercentage: 40,
    slaMinutes: 15,
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 3 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    startedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    isEscalated: true,
    escalationLevel: 1,
    escalatedTo: "رئيس قسم العناية المركزة",
    requiresApproval: true,
    payload: {
      testName: "Serum Potassium",
      value: "6.8",
      unit: "mmol/L",
      referenceRange: "3.5 - 5.1",
      deltaCheck: "+2.1 from previous 4.7"
    },
    notes: [
      {
        id: "n-1",
        authorId: "usr-lab-01",
        authorName: "أمل الشمري",
        role: "Lab Tech",
        content: "تم تأكيد الفحص مرتين على جهاز Cobas c501.",
        timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString()
      }
    ],
    attachments: [],
    auditLogs: [
      {
        id: "a-1",
        taskId: "task-001",
        action: "TASK_CREATED_AUTO",
        performedBy: "SYSTEM_AUTO_ENGINE",
        performedByName: "Auto Task Engine",
        newStatus: "new",
        timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
        details: "Auto triggered from LIS Critical Result Rule"
      },
      {
        id: "a-2",
        taskId: "task-001",
        action: "TASK_ESCALATED",
        performedBy: "SYSTEM_SLA_MONITOR",
        performedByName: "SLA Auto Escalation",
        previousStatus: "in_progress",
        newStatus: "escalated",
        timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
        details: "Escalated due to 15m SLA approach limit without completion"
      }
    ],
    isAutoGenerated: true,
    triggerEvent: "critical_result_flagged"
  },
  {
    id: "task-002",
    taskNumber: "TSK-2026-002",
    titleAr: "تفعيل كود أزرق Code Blue - غرفة 302",
    titleEn: "Code Blue Activation - Ward Room 302 Bed 1",
    descriptionAr: "توقف قلبي تنفسي طارئ. استجابة فورية للفريق الطبي و RRT.",
    descriptionEn: "Cardiopulmonary arrest. Immediate RRT & Resuscitation team response required.",
    category: "clinical",
    subtype: "physician",
    priority: "code_blue",
    status: "in_progress",
    originDepartment: "nursing",
    targetDepartment: "er",
    assignedToUserId: "rrt-team-leader",
    assignedToUserName: "قائد فريق الإنقاذ السريع",
    assignedToRole: "RRT Leader",
    createdById: "nurse-302",
    createdByName: "ممرض الجناح - سارة علي",
    patientId: "p2",
    patientMRN: "MRN-100567",
    patientNameAr: "فاطمة محمد العلي",
    patientNameEn: "Fatima Mohammed Al-Ali",
    visitId: "vst-002",
    bedId: "bed-302-1",
    roomId: "302",
    progressPercentage: 60,
    slaMinutes: 3,
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 1 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 1.5 * 60 * 1000).toISOString(),
    startedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    isEscalated: true,
    escalationLevel: 2,
    requiresApproval: false,
    notes: [],
    attachments: [],
    auditLogs: [],
    isAutoGenerated: true,
    triggerEvent: "code_blue_triggered"
  },
  {
    id: "task-003",
    taskNumber: "TSK-2026-003",
    titleAr: "تأكيد طلب دواء عالي الخطورة - Insulating Infusion",
    titleEn: "High-Alert Medication Verification - Insulin Drip",
    descriptionAr: "مراجعة الجرعة المزدوجة وصرف دواء الأنسولين الوريدي لمريض العناية.",
    descriptionEn: "Independent double-check & dispensing of IV Insulin drip for ICU patient.",
    category: "pharmacy",
    subtype: "verify_prescription",
    priority: "stat",
    status: "assigned",
    originDepartment: "icu",
    targetDepartment: "pharmacy",
    assignedToUserId: "pharm-02",
    assignedToUserName: "د. مريم الغامدي (صيدلي أول)",
    assignedToRole: "Clinical Pharmacist",
    createdById: "doc-icu-02",
    createdByName: "د. طارق السعيد",
    patientId: "p1",
    patientMRN: "MRN-100234",
    patientNameAr: "يوسف أحمد الخالدي",
    patientNameEn: "Youssef Ahmed Al-Khaldi",
    progressPercentage: 20,
    slaMinutes: 20,
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
    isEscalated: false,
    escalationLevel: 0,
    requiresApproval: true,
    notes: [],
    attachments: [],
    auditLogs: [],
    isAutoGenerated: true,
    triggerEvent: "medication_prescribed"
  },
  {
    id: "task-004",
    taskNumber: "TSK-2026-004",
    titleAr: "تجهيز المريض لعملية جراحية - استئصال الزائدة",
    titleEn: "Pre-Operative Preparation - Appendectomy",
    descriptionAr: "تجهيز المريض، الفحوصات الجراحية، الموافقة المسبقة وتطهير موضع الجراحة.",
    descriptionEn: "Patient prep, pre-op checklist, surgical consent verification and site prep.",
    category: "operating_room",
    subtype: "patient_prep",
    priority: "urgent",
    status: "in_progress",
    originDepartment: "er",
    targetDepartment: "or",
    assignedToUserId: "nurse-or-01",
    assignedToUserName: "ممرض عمليات - بدر المطيري",
    createdById: "doc-surg-01",
    createdByName: "د. عبد الله الماجد",
    patientId: "p3",
    patientMRN: "MRN-100890",
    patientNameAr: "سعود الحربي",
    patientNameEn: "Saud Al-Harbi",
    progressPercentage: 50,
    slaMinutes: 45,
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 25 * 60 * 1000).toISOString(),
    isEscalated: false,
    escalationLevel: 0,
    requiresApproval: true,
    notes: [],
    attachments: [],
    auditLogs: [],
    isAutoGenerated: true,
    triggerEvent: "surgery_scheduled"
  },
  {
    id: "task-005",
    taskNumber: "TSK-2026-005",
    titleAr: "فحص صيانة معايرة لجهاز التنفس الاصطناعي ICU-V03",
    titleEn: "Biomedical Calibration Check - Ventilator ICU-V03",
    descriptionAr: "صيانة وقائية دورية ومعايرة مستشعرات الأكسجين والضغط.",
    descriptionEn: "Routine preventive maintenance & sensor calibration for ICU ventilator.",
    category: "maintenance",
    subtype: "device_maintenance",
    priority: "high",
    status: "new",
    originDepartment: "icu",
    targetDepartment: "biomedical",
    assignedToUserId: "bio-tech-01",
    assignedToUserName: "مهندس طبي - فهد الدوسري",
    createdById: "SYSTEM_SCHEDULER",
    createdByName: "مجدول الصيانة الآلي",
    progressPercentage: 0,
    slaMinutes: 120,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 90 * 60 * 1000).toISOString(),
    isEscalated: false,
    escalationLevel: 0,
    requiresApproval: false,
    notes: [],
    attachments: [],
    auditLogs: [],
    isAutoGenerated: true,
    triggerEvent: "maintenance_due"
  },
  {
    id: "task-006",
    taskNumber: "TSK-2026-006",
    titleAr: "تصوير أشعة مقطعية طارئة للدماغ CT Brain STAT",
    titleEn: "STAT CT Brain Scan - Suspected Stroke",
    descriptionAr: "شبهة جلطة دماغية حادة. إجراء الأشعة ونقل الصور فوراً لنظام RIS/PACS.",
    descriptionEn: "Acute stroke protocol. Perform non-contrast CT Brain and push immediately to PACS.",
    category: "radiology",
    subtype: "perform_scan",
    priority: "stat",
    status: "accepted",
    originDepartment: "er",
    targetDepartment: "ris",
    assignedToUserId: "rad-tech-01",
    assignedToUserName: "فني أشعة - عمر العمري",
    createdById: "doc-er-01",
    createdByName: "د. سامي القحطاني",
    patientId: "p4",
    patientMRN: "MRN-101122",
    patientNameAr: "نورة الدوسري",
    patientNameEn: "Noura Al-Dossary",
    progressPercentage: 30,
    slaMinutes: 30,
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 20 * 60 * 1000).toISOString(),
    isEscalated: false,
    escalationLevel: 0,
    requiresApproval: false,
    notes: [],
    attachments: [],
    auditLogs: [],
    isAutoGenerated: true,
    triggerEvent: "stroke_alert"
  }
];

// Event listeners for task updates
type TaskChangeListener = (tasks: EnterpriseTask[]) => void;
const listeners: TaskChangeListener[] = [];

export const subscribeToEnterpriseTasks = (listener: TaskChangeListener) => {
  listeners.push(listener);
  listener([...mockEnterpriseTasks]);
  return () => {
    const idx = listeners.indexOf(listener);
    if (idx > -1) listeners.splice(idx, 1);
  };
};

const notifyListeners = () => {
  listeners.forEach(fn => fn([...mockEnterpriseTasks]));
};

export const getEnterpriseTasks = () => [...mockEnterpriseTasks];

// Create manual or auto task
export const createEnterpriseTask = (taskData: Partial<EnterpriseTask>): EnterpriseTask => {
  const newTask: EnterpriseTask = {
    id: `task-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
    taskNumber: `TSK-2026-${Math.floor(100 + Math.random() * 900)}`,
    titleAr: taskData.titleAr || "مهمة جديدة",
    titleEn: taskData.titleEn || "New Task",
    descriptionAr: taskData.descriptionAr || "",
    descriptionEn: taskData.descriptionEn || "",
    category: taskData.category || "clinical",
    subtype: taskData.subtype || "general",
    priority: taskData.priority || "normal",
    status: taskData.status || "new",
    originDepartment: taskData.originDepartment || "administration",
    targetDepartment: taskData.targetDepartment || "nursing",
    assignedToUserId: taskData.assignedToUserId,
    assignedToUserName: taskData.assignedToUserName,
    assignedToRole: taskData.assignedToRole,
    createdById: taskData.createdById || "USR-CURRENT",
    createdByName: taskData.createdByName || "المستخدم الحالي",
    patientId: taskData.patientId,
    patientMRN: taskData.patientMRN,
    patientNameAr: taskData.patientNameAr,
    patientNameEn: taskData.patientNameEn,
    visitId: taskData.visitId,
    orderId: taskData.orderId,
    bedId: taskData.bedId,
    roomId: taskData.roomId,
    progressPercentage: taskData.progressPercentage || 0,
    slaMinutes: taskData.slaMinutes || 60,
    createdAt: new Date().toISOString(),
    dueAt: new Date(Date.now() + (taskData.slaMinutes || 60) * 60 * 1000).toISOString(),
    isEscalated: false,
    escalationLevel: 0,
    requiresApproval: taskData.requiresApproval || false,
    payload: taskData.payload || {},
    notes: taskData.notes || [],
    attachments: taskData.attachments || [],
    auditLogs: [
      {
        id: `aud-${Date.now()}`,
        taskId: "",
        action: taskData.isAutoGenerated ? "AUTO_TRIGGER_CREATED" : "MANUAL_TASK_CREATED",
        performedBy: taskData.createdById || "USR-CURRENT",
        performedByName: taskData.createdByName || "المستخدم الحالي",
        newStatus: taskData.status || "new",
        timestamp: new Date().toISOString(),
        details: `Task created. Category: ${taskData.category}, Target Dept: ${taskData.targetDepartment}`
      }
    ],
    isAutoGenerated: taskData.isAutoGenerated || false,
    triggerEvent: taskData.triggerEvent
  };

  newTask.auditLogs[0].taskId = newTask.id;
  mockEnterpriseTasks = [newTask, ...mockEnterpriseTasks];
  notifyListeners();
  return newTask;
};

// Auto-trigger engine based on hospital events
export const triggerAutoTaskEngine = (
  event: AutoTaskTriggerEvent,
  contextData: {
    patientId?: string;
    patientMRN?: string;
    patientNameAr?: string;
    patientNameEn?: string;
    department?: HospitalDepartmentId;
    orderId?: string;
    detailsAr?: string;
    detailsEn?: string;
    value?: string;
  }
) => {
  let titleAr = "";
  let titleEn = "";
  let category: TaskCategory = "clinical";
  let targetDept: HospitalDepartmentId = "nursing";
  let priority: TaskPriority = "normal";
  let slaMinutes = 60;

  switch (event) {
    case "code_blue_triggered":
      titleAr = `تفعيل كود أزرق Code Blue - ${contextData.detailsAr || "قسم العناية"}`;
      titleEn = `Code Blue Activated - ${contextData.detailsEn || "ICU / Ward"}`;
      priority = "code_blue";
      slaMinutes = 3;
      category = "clinical";
      targetDept = "er";
      break;
    case "critical_result_flagged":
      titleAr = `إشعار نتيجة تحليل حرجة - ${contextData.value || "الدم"}`;
      titleEn = `Critical Laboratory Result Flagged - ${contextData.value || "Blood"}`;
      priority = "critical";
      slaMinutes = 15;
      category = "laboratory";
      targetDept = "icu";
      break;
    case "stroke_alert":
      titleAr = "إنذار جلطة دماغية حادة Stroke Alert - تصوير مقطعي عاجل";
      titleEn = "Stroke Alert - Immediate Non-contrast CT Scan";
      priority = "stat";
      slaMinutes = 20;
      category = "radiology";
      targetDept = "ris";
      break;
    case "low_stock_warning":
      titleAr = `تنبيه انخفاض مخزون دواء/مستلزم: ${contextData.value || "مستلزمات حادة"}`;
      titleEn = `Low Inventory Stock Level: ${contextData.value || "Medical Supplies"}`;
      priority = "high";
      slaMinutes = 120;
      category = "pharmacy";
      targetDept = "pharmacy";
      break;
    default:
      titleAr = `مهمة تلقائية: ${event}`;
      titleEn = `Auto Task: ${event}`;
      break;
  }

  return createEnterpriseTask({
    titleAr,
    titleEn,
    descriptionAr: contextData.detailsAr || titleAr,
    descriptionEn: contextData.detailsEn || titleEn,
    category,
    originDepartment: contextData.department || "administration",
    targetDepartment: targetDept,
    priority,
    slaMinutes,
    patientId: contextData.patientId,
    patientMRN: contextData.patientMRN,
    patientNameAr: contextData.patientNameAr,
    patientNameEn: contextData.patientNameEn,
    orderId: contextData.orderId,
    isAutoGenerated: true,
    triggerEvent: event
  });
};

// 13-Step Workflow state updates
export const updateTaskWorkflowState = (
  taskId: string,
  newStatus: TaskStatus,
  actionData: {
    performedBy: string;
    performedByName: string;
    noteContent?: string;
    progressPercentage?: number;
    assignedToUser?: { id: string; name: string };
    attachment?: { fileName: string; fileType: string; fileUrl: string };
  }
) => {
  mockEnterpriseTasks = mockEnterpriseTasks.map(task => {
    if (task.id !== taskId) return task;

    const oldStatus = task.status;
    const now = new Date().toISOString();
    const updatedNotes = [...task.notes];
    const updatedAttachments = [...task.attachments];

    if (actionData.noteContent) {
      updatedNotes.push({
        id: `note-${Date.now()}`,
        authorId: actionData.performedBy,
        authorName: actionData.performedByName,
        role: "Staff",
        content: actionData.noteContent,
        timestamp: now
      });
    }

    if (actionData.attachment) {
      updatedAttachments.push({
        id: `att-${Date.now()}`,
        fileName: actionData.attachment.fileName,
        fileType: actionData.attachment.fileType,
        fileUrl: actionData.attachment.fileUrl,
        uploadedBy: actionData.performedByName,
        uploadedAt: now
      });
    }

    const auditLog = {
      id: `aud-${Date.now()}`,
      taskId,
      action: `STATUS_CHANGE_${newStatus.toUpperCase()}`,
      performedBy: actionData.performedBy,
      performedByName: actionData.performedByName,
      previousStatus: oldStatus,
      newStatus,
      timestamp: now,
      details: `Status transitioned from ${oldStatus} to ${newStatus}`
    };

    return {
      ...task,
      status: newStatus,
      progressPercentage: actionData.progressPercentage !== undefined ? actionData.progressPercentage : (newStatus === "completed" || newStatus === "closed" ? 100 : task.progressPercentage),
      assignedToUserId: actionData.assignedToUser ? actionData.assignedToUser.id : task.assignedToUserId,
      assignedToUserName: actionData.assignedToUser ? actionData.assignedToUser.name : task.assignedToUserName,
      acceptedAt: newStatus === "accepted" ? now : task.acceptedAt,
      startedAt: newStatus === "in_progress" ? now : task.startedAt,
      completedAt: newStatus === "completed" ? now : task.completedAt,
      verifiedAt: newStatus === "verified" ? now : task.verifiedAt,
      closedAt: newStatus === "closed" ? now : task.closedAt,
      notes: updatedNotes,
      attachments: updatedAttachments,
      auditLogs: [auditLog, ...task.auditLogs]
    };
  });

  notifyListeners();
};
